Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace ByteClubSite.Models
{
    public class Schedule
    {
        public string Name { get; set; } //Class name
        public int Period { get; set; } //Period Number (auto-increment?)
        public bool isEmpty { get; set; } //Is there a class here
        public string Start { get; set; } //Start time (ex: 23:59)
        public string StartLate { get; set; } //Start time on Late Start
        public string StartEarlyDismiss { get; set; } //Start time on Early Dismissal
    }
}

Models/Screen.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ByteClubSite.Models
{
    public class Screen
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Class { get; set; }
        [Required]
        public string Body { get; set; }
        //Maybe have templated rows where user just types in assignment name and details
        //Have "No class" checkbox; generate empty instance
    }
}

Pages/Screen/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using ByteClubSite.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ByteClubSite.Pages.Screen
{
    public class EditModel : PageModel
    {

        private IWebHostEnvironment _environment;
        private readonly ApplicationDbContext _db;
        public EditModel(IWebHostEnvironment environment, ApplicationDbContext db)
        {
            _environment = environment;
            _db = db;
        }

        [BindProperty]
        public IFormFile Upload { get; set; } //Thing to check if there is a file specified in the form

        [BindProperty]
        public Agenda Agenda { get; set; }
        public string displayClass { get; set; } //for display on page
        public int displayPeriod { get; set; } //for display on page
        public async Task<IActionResult> OnGet(int id)
        {
            if (HttpContext.Session.GetInt32("access") < 1 || HttpContext.Session.GetInt32("access") == null)
            {
                return RedirectToPage("/ErrorAccessDenied");
            }
            Agenda = await _db.Agenda.FindAsync(id);

            displayClass = Agenda.Class;
            displayPeriod = Agenda.Id;
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (Upload != null) //If there is a file specified in form
            {
                var file = Path.Combine(_environment.ContentRootPath, "wwwroot/img/uploads", Upload.FileName); //Set upload path
                using (var fileStream = new FileStream(file, FileMode.Create)) //Make file-uploader
                {
                    await Upload.CopyToAsync(fileStream); //upload file
                    fileStream.Close();
                }
            }
            if (ModelState.IsValid)
            {
                var ClassFromDb = await _db.Agenda.FindAsync(Agenda.Id);
                ClassFromDb.Class = Agenda.Class;
                ClassFromDb.Body = Agenda.Body;

                await _db.SaveChangesAsync();

                return RedirectToPage("Index");
            }
            else
            {
                return RedirectToPage("Index");
            }
        }
    }
}

Pages/Screen/EditSchedule.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ByteClubSite.Models;
using Microsoft.EntityFrameworkCore;

namespace ByteClubSite.Pages.Screen
{
    public class EditScheduleModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public EditScheduleModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public List<Agenda> Agendas { get; set; }
        public async Task<IActionResult> OnGet()
        {
            Agendas = await _db.Agenda.ToListAsync();
            return Page();
        }
        public async Task<IActionResult> OnPost()
        {
            foreach (Agenda data in Agendas)
            {
                if (!data.Active)
                {
                    data.Class = "No Class Scheduled."; data.Body = " "; //Clear agenda view if there is no class
                }
            }
            int i = 1; //Yes I know incrementing a variable inside a for loop makes no sense, but just using data.Id doesn't work for reasons I don't quite understand
            //EDIT: It was because SQL tables do not start from 0
            foreach (Agenda data in Agendas)
            {
                if (ModelState.IsValid)
                {
                    var AgendaFromDb = _db.Agenda.Find(i);
                    AgendaFromDb.Class = data.Class;
                    AgendaFromDb.Body = data.Body;
                    AgendaFromDb.StartTime = data.StartTime;
                    AgendaFromDb.StartLate = data.StartLate;
                    AgendaFromDb.StartEarlyDismiss = data.StartEarlyDismiss;
                    AgendaFromDb.StartActivity = data.StartActivity;
                    AgendaFromDb.Active = data.Active;
                    await _db.SaveChangesAsync();
                }
                else
                {
                    return RedirectToPage("EditSchedule");
                }
                i++;
            }
            return RedirectToPage("Index");
        }
    }
}

Pages/Screen/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ByteClubSite.Models;
using Microsoft.EntityFrameworkCore;

namespace ByteClubSite.Pages.Screen
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public List<Agenda> Agendas;
        public List<long> AgendasList = new List<long>();
        public int ScheduleTimings = 0;
        public int CurrentClassIndex = 0;
        public async Task OnGet()
        {
            var jsonFileReader = System.IO.File.OpenText("Pages/Screen/data/schedule.csv");
            ScheduleTimings = jsonFileReader.ReadToEnd().Split("\n")[0][5] - 48;
            jsonFileReader.Close();

            Agendas = await _db.Agenda.ToListAsync();

            foreach (var item in Agendas)
            {
                DateTime temp = DateTime.Now.Date; //Today but time is set to midnight
                if (ScheduleTimings == 0)
                {
                    temp += item.StartTime;
                }
                else if (ScheduleTimings == 1)
                {
                    temp += item.StartLate;
                }
                else if (ScheduleTimings == 2)
                {
                    temp += item.StartEarlyDismiss;
                }
                else if (ScheduleTimings == 3)
                {
                    temp += item.StartActivity;
                }

                AgendasList.Add((long)(temp - new DateTime(1970, 1, 1)).TotalMilliseconds);
            }
        }
    }
}

Pages/Screen/Manage.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ByteClubSite.Pages.Screen
{
    public class ManageModel : PageModel
    {
        public List<string> jsonStr = new List<string>();
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("access") < 1 || HttpContext.Session.GetInt32("access") == null)
            {
                return RedirectToPage("/ErrorAccessDenied");
            }
            var jsonFileReader = System.IO.File.OpenText("Pages/Screen/data/schedule.csv");
            jsonStr = jsonFileReader.ReadToEnd().Split("\n").ToList();
            jsonFileReader.Close();
            return Page();
        }
        public async Task OnGetChangeScheduleTimings(int s)
        {
            var jsonFileReader = System.IO.File.OpenText("Pages/Screen/data/schedule.csv");
            jsonStr = jsonFileReader.ReadToEnd().Split("\n").ToList();
            jsonFileReader.Close();
            jsonStr[0] = "type:" + s;
            foreach (var item in jsonStr)
            {
                await System.IO.File.WriteAllTextAsync("Pages/Screen/data/schedule.csv", item);
            }
        }
    }
}

Pages/Screen/Schedule.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ByteClubSite.Pages.Screen
{
    public class ScheduleModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Screen/Static.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ByteClubSite.Pages.Screen
{
    public class StaticModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Screen/Edit.cshtml
@page
@model ByteClubSite.Pages.Screen.EditModel
@{
}

<br />
<h2></h2>
<h2 class="text-info">Edit Post</h2>
<br />

<div class="border container" style="padding:20px">
    <form method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="Agenda.Id" />
        <input type="hidden" asp-for="Agenda.Class" />
        <input type="hidden" asp-for="Agenda.StartTime" />
        <input type="hidden" asp-for="Agenda.StartLate" />
        <input type="hidden" asp-for="Agenda.StartEarlyDismiss" />
        <input type="hidden" asp-for="Agenda.StartActivity" />
        <h4 class="text-light">Period @Model.displayPeriod</h4>
        <h2 class="text-light">@Model.displayClass</h2>
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Agenda.Body" class="text-light"></label>
            </div>
            <div class="col-6">
                <textarea rows="10" cols="90" asp-for="Agenda.Body" class="form-control"></textarea>
            </div>
            <br />
            <span asp-validation-for="Agenda.Body" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Upload" class="text-light"></label>
            </div>
            <div class="col-6">
                <input type="file" multiple asp-for="Upload" class="form-control" />
            </div>
            <br />
            <span asp-validation-for="Upload" class="text-danger"></span>
        </div>
        <p class="text-warning">Note: HTML media tags (img, video, etc.) must source to "img/uploads/(Image Name)"</p>
        <div class="form-group row">
            <div class="col-3 offset-4">
                <input type="submit" value="Update" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Manage" class="btn btn-success form-control">Back to Agenda Manage</a>
            </div>
        </div>
    </form>
</div>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Pages/Screen/EditSchedule.cshtml
@page
@model ByteClubSite.Pages.Screen.EditScheduleModel
@{ }
@using ByteClubSite.Models;
<form method="post" enctype="multipart/form-data">
    <table id="DT_load" class="table table-striped table-bordered text-light" style="width:100%">
        <thead>
            <tr>
                <th>Period</th>
                <th>Class</th>
                <th>Start Time</th>
                <th>Start Time (late Start)</th>
                <th>Start Time (Early Dismiss)</th>
                <th>Start Time (Activity Schedule)</th>
                <th>Active</th>
            </tr>
            @{ 
                for (int i = 0; i < Model.Agendas.Count(); i++)
                {
                        <tr>
                            <td>@Model.Agendas[i].Id</td>
                            <td>
                                <div>
                                    @{ //This part checks if the Agenda is active, and adds the disabled attribute as necessary
                                        if (Model.Agendas[i].Active)
                                        {
                                            <input asp-for="@Model.Agendas[i].Class" class="form-control" id="@(Model.Agendas[i].Id + "" + 'a')" />
                                        }
                                        else
                                        {
                                            <input asp-for="@Model.Agendas[i].Class" class="form-control" id="@(Model.Agendas[i].Id + "" + 'a')" disabled value="Inactive"/>
                                        }
                                    }
                                </div>
                                <br />
                                <span asp-validation-for="@Model.Agendas[i].Class" class="text-danger"></span>
                            </td>
                            <td style="display: none"><input type="hidden" asp-for="@Model.Agendas[i].Body" /></td>
                            <td>
                                <div>
                                    <input asp-for="@Model.Agendas[i].StartTime" class="form-control" type="time" />
                                </div>
                                <br />
                                <span asp-validation-for="@Model.Agendas[i].StartTime" class="text-danger"></span>
                            </td>
                            <td>
                                <div>
                                    <input asp-for="@Model.Agendas[i].StartLate" class="form-control" type="time" />
                                </div>
                                <br />
                                <span asp-validation-for="@Model.Agendas[i].StartLate" class="text-danger"></span>
                            </td>
                            <td>
                                <div>
                                    <input asp-for="@Model.Agendas[i].StartEarlyDismiss" class="form-control" type="time" />
                                </div>
                                <br />
                                <span asp-validation-for="@Model.Agendas[i].StartEarlyDismiss" class="text-danger"></span>
                            </td>
                            <td>
                                <div>
                                    <input asp-for="@Model.Agendas[i].StartActivity" class="form-control" type="time" />
                                </div>
                                <br />
                                <span asp-validation-for="@Model.Agendas[i].StartActivity" class="text-danger"></span>
                            </td>
                            <td>
                                <div>
                                    <input asp-for="@Model.Agendas[i].Active" class="form-control" type="checkbox" id="@(Model.Agendas[i].Id + "" + 'b')"/>
                                </div>
                                <br />
                                <span asp-validation-for="@Model.Agendas[i].Active" class="text-danger"></span>
                            </td>
                        </tr>
                }
            }
        </thead>
    </table>
    <input type="submit" value="Update" class="btn btn-primary form-control" />
</form>




@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    @{ 
        for (int i = 0; i < Model.Agendas.Count(); i++)
        {
        <script>
                $('#' + @Model.Agendas[i].Id + 'b').on('change', function () {
                    console.log("a " + $('#' + @Model.Agendas[i].Id + 'b:checked').val());
                    if (!$('#' + @Model.Agendas[i].Id + 'b:checked').val()) {
                        $('#' + @Model.Agendas[i].Id + 'a').val('Inactive');
                        $('#' + @Model.Agendas[i].Id + 'a').attr('disabled', "true");
                        console.log("if");
                    }
                    else {
                        $('#' + @Model.Agendas[i].Id + 'a').removeAttr('disabled');
                        console.log("else");
                    }
                });
        </script>
        }
    }
}

Pages/Screen/Index.cshtml
@page
@model ByteClubSite.Pages.Screen.IndexModel
@{
    ViewData["Title"] = "Class Assignments";
}
<style>
    header, footer {
        display: none;
    }
    .classes {
        width: 100%;
        margin: 5vh 0 5vh 0;
    }
    .currentClass {
        width: 100%;
        display: flex;
        flex-direction: column;
    }
    .currentClass_header {
        width: 100%;
        display: flex;
        flex-direction: row;
        align-items: baseline;
        justify-content: space-between;

        border-bottom: 1px solid #FFF;
        margin-bottom: 2vh;
    }
    .currentClass_header h1 {
        font-size: 450%;
        padding-left: 20px;
    }
    .currentClass_header h4 {
        font-size: 170%;
        padding-right: 20px;
    }

</style>

<div class="classes">
    <div class="currentClass text-light">
        <div class="currentClass_header">
            <h1 id="dataClass"></h1>
            <h4 id="dataIndex"></h4>
        </div>
        <div class="currentClass_body" id="dataBody"></div>
    </div>
    @*@{
        foreach (var item in Model.Agendas)
        {
            <p class="text-light">@item.StartTime</p>
        }
        <p>@Model.AgendasList</p>
    }*@
</div>

@section Scripts {
    @*<script src="~/js/ScreenTimes.js"></script>*@
<script>
    var startTimes = JSON.parse('@Html.Raw(Json.Serialize(Model.AgendasList))'); //List of start times as milliseconds since EPOC
    console.log(startTimes);
    console.log(@Model.ScheduleTimings);
    var dateNow = new Date();
    var currentClass, nextClass; //Indexes of classes
    var currentData; //Data for current class
    for (var i = 0; i < startTimes.length; i++) {
        console.log("loop");
        if (dateNow.getTime() > startTimes[i] && i == 7) { //Current time is period 8 or after school
            currentClass = i;
            nextClass = 0;
            startTimes[0] += 86400000; //Start time is at period 1 time tomorrow
            break;
        }
        else if (dateNow.getTime() > startTimes[i] && dateNow.getTime() < startTimes[i + 1]) {
            currentClass = i;
            nextClass = i + 1;
            break;
        }
    }
    var dataString = '@Html.Raw(Json.Serialize(Model.Agendas))';
    // preserve newlines, etc - use valid JSON
    dataString = dataString.replace(/\\n/g, "\\n")
        .replace(/\\'/g, "\\'")
        .replace(/\\"/g, '\\"')
        .replace(/\\&/g, "\\&")
        .replace(/\\r/g, "\\r")
        .replace(/\\t/g, "\\t")
        .replace(/\\b/g, "\\b")
        .replace(/\\f/g, "\\f");
    // remove non-printable and other non-valid JSON chars
    dataString = dataString.replace(/[\u0000-\u0019]+/g, "");
    var currentData = JSON.parse(dataString)[currentClass]; //Get data for current class
    document.getElementById('dataClass').innerHTML = currentData.class;
    document.getElementById('dataIndex').innerHTML = "Period " + currentData.id;
    document.getElementById('dataBody').innerHTML = currentData.body;

    function refreshPage() {
        location.reload(true);
    }

    setTimeout(refreshPage, startTimes[nextClass] - Date.now()); //Refresh the page after the amount of time to get to next period start time

</script>
}

Pages/Screen/Manage.cshtml
@page
@model ByteClubSite.Pages.Screen.ManageModel
@{
}

<table id="DT_load" class="table table-striped table-bordered text-light" style="width:100%">
    <thead>
        <tr>
            <th>Class</th>
            <th>Body</th>
            <th></th>
        </tr>
    </thead>
</table>
<br />
<div class="text-light">
    @{ 
        if (Model.jsonStr[0].Equals("type:0"))
        {
        <p>Current Schedule Type: Normal</p>
        }
        else if (Model.jsonStr[0].Equals("type:1"))
        {
        <p>Current Schedule Type: Late Start</p>
        }
        else if (Model.jsonStr[0].Equals("type:2"))
        {
        <p>Current Schedule Type: Early Dismissal</p>
        }
        else if (Model.jsonStr[0].Equals("type:3"))
        {
        <p>Current Schedule Type: Activity</p>
        }
        else
        {
        <p>@Model.jsonStr[0]</p>
        }
    }
<div style="display: flex; flex-direction: row; justify-content: space-evenly;">
    <p><a class="btn btn-light" asp-page-handler="ChangeScheduleTimings" asp-route-s="0">Enable Normal Schedule</a></p>
    <p><a class="btn btn-light" asp-page-handler="ChangeScheduleTimings" asp-route-s="1">Enable Late Start Schedule</a></p>
    <p><a class="btn btn-light" asp-page-handler="ChangeScheduleTimings" asp-route-s="2">Enable Early Dismissal Schedule</a></p>
    <p><a class="btn btn-light" asp-page-handler="ChangeScheduleTimings" asp-route-s="3">Enable Activity Schedule</a></p>
    <p><a class="btn btn-success" asp-page="EditSchedule">Edit Schedule Times</a></p>
</div>
</div>

@section Scripts{
    <script src="~/js/ManageAgenda.js"></script>
}

Pages/Screen/Schedule.cshtml
@page
@model ByteClubSite.Pages.Screen.ScheduleModel
@{ }
<div class="currentClass text-light">
    <h2 class="className">Class Name</h2>
    <p class="classDetails">Assignment </p>
</div>

Pages/Screen/Static.cshtml
@page
@model ByteClubSite.Pages.Screen.StaticModel
@{
}
<div class="currentClass text-light">
    <h2 class="className">Class Name</h2>
    <p class="classDetails">Assignment </p>
</div>